create table CSKT
(
    MANDT nvarchar(3)  not null,
    SPRAS nvarchar     not null,
    KOKRS nvarchar(4)  not null,
    KOSTL nvarchar(10) not null,
    DATBI nvarchar(8)  not null,
    KTEXT nvarchar(20) not null,
    LTEXT nvarchar(40) not null,
    MCTXT nvarchar(20) not null,
    constraint [CSKT~0]
        primary key (MANDT, SPRAS, KOKRS, KOSTL, DATBI)
)
go
-- auto-generated definition
create table gsp.HRP1000
(
    MANDT    nvarchar(3)  not null,
    PLVAR    nvarchar(2)  not null,
    OTYPE    nvarchar(2)  not null,
    OBJID    nvarchar(8)  not null,
    ISTAT    nvarchar     not null,
    BEGDA    nvarchar(8)  not null,
    ENDDA    nvarchar(8)  not null,
    LANGU    nvarchar     not null,
    SEQNR    nvarchar(3)  not null,
    OTJID    nvarchar(10) not null,
    INFTY    nvarchar(4)  not null,
    AEDTM    nvarchar(8)  not null,
    UNAME    nvarchar(12) not null,
    REASN    nvarchar(2)  not null,
    HISTO    nvarchar     not null,
    ITXNR    nvarchar(8)  not null,
    SHORT    nvarchar(12) not null,
    STEXT    nvarchar(40) not null,
    GDATE    nvarchar(8)  not null,
    MC_SHORT nvarchar(12) not null,
    MC_STEXT nvarchar(40) not null,
    MC_SEARK nvarchar(52) not null,
    constraint [HRP1000~0]
        primary key (MANDT, PLVAR, OTYPE, OBJID, ISTAT, BEGDA, ENDDA, LANGU, SEQNR)
)
go
create table PA0000
(
    MANDT nvarchar(3)  not null,
    PERNR nvarchar(8)  not null,
    SUBTY nvarchar(4)  not null,
    OBJPS nvarchar(2)  not null,
    SPRPS nvarchar     not null,
    ENDDA nvarchar(8)  not null,
    BEGDA nvarchar(8)  not null,
    SEQNR nvarchar(3)  not null,
    AEDTM nvarchar(8)  not null,
    UNAME nvarchar(12) not null,
    HISTO nvarchar     not null,
    ITXEX nvarchar     not null,
    REFEX nvarchar     not null,
    ORDEX nvarchar     not null,
    ITBLD nvarchar(2)  not null,
    PREAS nvarchar(2)  not null,
    FLAG1 nvarchar     not null,
    FLAG2 nvarchar     not null,
    FLAG3 nvarchar     not null,
    FLAG4 nvarchar     not null,
    RESE1 nvarchar(2)  not null,
    RESE2 nvarchar(2)  not null,
    GRPVL nvarchar(4)  not null,
    MASSN nvarchar(2)  not null,
    MASSG nvarchar(2)  not null,
    STAT1 nvarchar     not null,
    STAT2 nvarchar     not null,
    STAT3 nvarchar     not null,
    constraint [PA0000~0]
        primary key (MANDT, PERNR, SUBTY, OBJPS, SPRPS, ENDDA, BEGDA, SEQNR)
)
go

create table PA0001
(
    MANDT     nvarchar(3)  not null,
    PERNR     nvarchar(8)  not null,
    SUBTY     nvarchar(4)  not null,
    OBJPS     nvarchar(2)  not null,
    SPRPS     nvarchar     not null,
    ENDDA     nvarchar(8)  not null,
    BEGDA     nvarchar(8)  not null,
    SEQNR     nvarchar(3)  not null,
    AEDTM     nvarchar(8)  not null,
    UNAME     nvarchar(12) not null,
    HISTO     nvarchar     not null,
    ITXEX     nvarchar     not null,
    REFEX     nvarchar     not null,
    ORDEX     nvarchar     not null,
    ITBLD     nvarchar(2)  not null,
    PREAS     nvarchar(2)  not null,
    FLAG1     nvarchar     not null,
    FLAG2     nvarchar     not null,
    FLAG3     nvarchar     not null,
    FLAG4     nvarchar     not null,
    RESE1     nvarchar(2)  not null,
    RESE2     nvarchar(2)  not null,
    GRPVL     nvarchar(4)  not null,
    BUKRS     nvarchar(4)  not null,
    WERKS     nvarchar(4)  not null,
    PERSG     nvarchar     not null,
    PERSK     nvarchar(2)  not null,
    VDSK1     nvarchar(14) not null,
    GSBER     nvarchar(4)  not null,
    BTRTL     nvarchar(4)  not null,
    JUPER     nvarchar(4)  not null,
    ABKRS     nvarchar(2)  not null,
    ANSVH     nvarchar(2)  not null,
    KOSTL     nvarchar(10) not null,
    ORGEH     nvarchar(8)  not null,
    PLANS     nvarchar(8)  not null,
    STELL     nvarchar(8)  not null,
    MSTBR     nvarchar(8)  not null,
    SACHA     nvarchar(3)  not null,
    SACHP     nvarchar(3)  not null,
    SACHZ     nvarchar(3)  not null,
    SNAME     nvarchar(30) not null,
    ENAME     nvarchar(40) not null,
    OTYPE     nvarchar(2)  not null,
    SBMOD     nvarchar(4)  not null,
    KOKRS     nvarchar(4)  not null,
    FISTL     nvarchar(16) not null,
    GEBER     nvarchar(10) not null,
    FKBER     nvarchar(16) not null,
    GRANT_NBR nvarchar(20) not null,
    SGMNT     nvarchar(10) not null,
    BUDGET_PD nvarchar(10) not null,
    constraint [PA0001~0]
        primary key (MANDT, PERNR, SUBTY, OBJPS, SPRPS, ENDDA, BEGDA, SEQNR)
)
go

create table PA0002
(
    MANDT    nvarchar(3)  not null,
    PERNR    nvarchar(8)  not null,
    SUBTY    nvarchar(4)  not null,
    OBJPS    nvarchar(2)  not null,
    SPRPS    nvarchar     not null,
    ENDDA    nvarchar(8)  not null,
    BEGDA    nvarchar(8)  not null,
    SEQNR    nvarchar(3)  not null,
    AEDTM    nvarchar(8)  not null,
    UNAME    nvarchar(12) not null,
    HISTO    nvarchar     not null,
    ITXEX    nvarchar     not null,
    REFEX    nvarchar     not null,
    ORDEX    nvarchar     not null,
    ITBLD    nvarchar(2)  not null,
    PREAS    nvarchar(2)  not null,
    FLAG1    nvarchar     not null,
    FLAG2    nvarchar     not null,
    FLAG3    nvarchar     not null,
    FLAG4    nvarchar     not null,
    RESE1    nvarchar(2)  not null,
    RESE2    nvarchar(2)  not null,
    GRPVL    nvarchar(4)  not null,
    INITS    nvarchar(10) not null,
    NACHN    nvarchar(40) not null,
    NAME2    nvarchar(40) not null,
    NACH2    nvarchar(40) not null,
    VORNA    nvarchar(40) not null,
    CNAME    nvarchar(80) not null,
    TITEL    nvarchar(15) not null,
    TITL2    nvarchar(15) not null,
    NAMZU    nvarchar(15) not null,
    VORSW    nvarchar(15) not null,
    VORS2    nvarchar(15) not null,
    RUFNM    nvarchar(40) not null,
    MIDNM    nvarchar(40) not null,
    KNZNM    nvarchar(2)  not null,
    ANRED    nvarchar     not null,
    GESCH    nvarchar     not null,
    GBDAT    nvarchar(8)  not null,
    GBLND    nvarchar(3)  not null,
    GBDEP    nvarchar(3)  not null,
    GBORT    nvarchar(40) not null,
    NATIO    nvarchar(3)  not null,
    NATI2    nvarchar(3)  not null,
    NATI3    nvarchar(3)  not null,
    SPRSL    nvarchar     not null,
    KONFE    nvarchar(2)  not null,
    FAMST    nvarchar     not null,
    FAMDT    nvarchar(8)  not null,
    ANZKD    decimal(3)   not null,
    NACON    nvarchar     not null,
    PERMO    nvarchar(2)  not null,
    PERID    nvarchar(20) not null,
    GBPAS    nvarchar(8)  not null,
    FNAMK    nvarchar(40) not null,
    LNAMK    nvarchar(40) not null,
    FNAMR    nvarchar(40) not null,
    LNAMR    nvarchar(40) not null,
    NABIK    nvarchar(40) not null,
    NABIR    nvarchar(40) not null,
    NICKK    nvarchar(40) not null,
    NICKR    nvarchar(40) not null,
    GBJHR    nvarchar(4)  not null,
    GBMON    nvarchar(2)  not null,
    GBTAG    nvarchar(2)  not null,
    NCHMC    nvarchar(25) not null,
    VNAMC    nvarchar(25) not null,
    NAMZ2    nvarchar(15) not null,
    ZZ_INDDI nvarchar     not null,
    ZZ_RESFA nvarchar     not null,
    constraint [PA0002~0]
        primary key (MANDT, PERNR, SUBTY, OBJPS, SPRPS, ENDDA, BEGDA, SEQNR)
)
go

create table PA0006
(
    MANDT        nvarchar(3)  not null,
    PERNR        nvarchar(8)  not null,
    SUBTY        nvarchar(4)  not null,
    OBJPS        nvarchar(2)  not null,
    SPRPS        nvarchar     not null,
    ENDDA        nvarchar(8)  not null,
    BEGDA        nvarchar(8)  not null,
    SEQNR        nvarchar(3)  not null,
    AEDTM        nvarchar(8)  not null,
    UNAME        nvarchar(12) not null,
    HISTO        nvarchar     not null,
    ITXEX        nvarchar     not null,
    REFEX        nvarchar     not null,
    ORDEX        nvarchar     not null,
    ITBLD        nvarchar(2)  not null,
    PREAS        nvarchar(2)  not null,
    FLAG1        nvarchar     not null,
    FLAG2        nvarchar     not null,
    FLAG3        nvarchar     not null,
    FLAG4        nvarchar     not null,
    RESE1        nvarchar(2)  not null,
    RESE2        nvarchar(2)  not null,
    GRPVL        nvarchar(4)  not null,
    ANSSA        nvarchar(4)  not null,
    NAME2        nvarchar(40) not null,
    STRAS        nvarchar(60) not null,
    ORT01        nvarchar(40) not null,
    ORT02        nvarchar(40) not null,
    PSTLZ        nvarchar(10) not null,
    LAND1        nvarchar(3)  not null,
    TELNR        nvarchar(14) not null,
    ENTKM        decimal(3)   not null,
    WKWNG        nvarchar     not null,
    BUSRT        nvarchar(3)  not null,
    LOCAT        nvarchar(40) not null,
    ADR03        nvarchar(40) not null,
    ADR04        nvarchar(40) not null,
    STATE        nvarchar(3)  not null,
    HSNMR        nvarchar(10) not null,
    POSTA        nvarchar(10) not null,
    BLDNG        nvarchar(10) not null,
    FLOOR        nvarchar(10) not null,
    STRDS        nvarchar(2)  not null,
    ENTK2        decimal(3)   not null,
    COM01        nvarchar(4)  not null,
    NUM01        nvarchar(20) not null,
    COM02        nvarchar(4)  not null,
    NUM02        nvarchar(20) not null,
    COM03        nvarchar(4)  not null,
    NUM03        nvarchar(20) not null,
    COM04        nvarchar(4)  not null,
    NUM04        nvarchar(20) not null,
    COM05        nvarchar(4)  not null,
    NUM05        nvarchar(20) not null,
    COM06        nvarchar(4)  not null,
    NUM06        nvarchar(20) not null,
    INDRL        nvarchar(2)  not null,
    COUNC        nvarchar(3)  not null,
    RCTVC        nvarchar(6)  not null,
    OR2KK        nvarchar(40) not null,
    CONKK        nvarchar(40) not null,
    OR1KK        nvarchar(40) not null,
    RAILW        nvarchar     not null,
    ZZ_CDPTO     nvarchar(2)  not null,
    ZZ_DDPTO     nvarchar(30) not null,
    ZZ_CPROV     nvarchar(2)  not null,
    ZZ_DPROV     nvarchar(30) not null,
    ZZ_CDIST     nvarchar(2)  not null,
    ZZ_DDIST     nvarchar(30) not null,
    ZZ_UBIG      nvarchar(6)  not null,
    ZZ_TVIA      nvarchar(2)  not null,
    ZZ_DVIA      nvarchar(30) not null,
    ZZ_CZON      nvarchar(2)  not null,
    ZZ_DZON      nvarchar(30) not null,
    ZZ_INTE      nvarchar(4)  not null,
    ZZ_MANZ      nvarchar(4)  not null,
    ZZ_LOTE      nvarchar(4)  not null,
    ZZ_KILO      nvarchar(4)  not null,
    ZZ_BLOC      nvarchar(4)  not null,
    ZZ_ETAP      nvarchar(4)  not null,
    ZZ_REFE      nvarchar(40) not null,
    ZZ_CODLARDIS nvarchar(2)  not null,
    ZZ_INDCEN    nvarchar     not null,
    ZZ_DSZON     nvarchar(20) not null,
    constraint [PA0006~0]
        primary key (MANDT, PERNR, SUBTY, OBJPS, SPRPS, ENDDA, BEGDA, SEQNR)
)
go

create table PA0016
(
    MANDT        nvarchar(3)  not null,
    PERNR        nvarchar(8)  not null,
    SUBTY        nvarchar(4)  not null,
    OBJPS        nvarchar(2)  not null,
    SPRPS        nvarchar     not null,
    ENDDA        nvarchar(8)  not null,
    BEGDA        nvarchar(8)  not null,
    SEQNR        nvarchar(3)  not null,
    AEDTM        nvarchar(8)  not null,
    UNAME        nvarchar(12) not null,
    HISTO        nvarchar     not null,
    ITXEX        nvarchar     not null,
    REFEX        nvarchar     not null,
    ORDEX        nvarchar     not null,
    ITBLD        nvarchar(2)  not null,
    PREAS        nvarchar(2)  not null,
    FLAG1        nvarchar     not null,
    FLAG2        nvarchar     not null,
    FLAG3        nvarchar     not null,
    FLAG4        nvarchar     not null,
    RESE1        nvarchar(2)  not null,
    RESE2        nvarchar(2)  not null,
    GRPVL        nvarchar(4)  not null,
    NBTGK        nvarchar     not null,
    WTTKL        nvarchar     not null,
    LFZFR        decimal(3)   not null,
    LFZZH        nvarchar(3)  not null,
    LFZSO        nvarchar(2)  not null,
    KGZFR        decimal(3)   not null,
    KGZZH        nvarchar(3)  not null,
    PRBZT        decimal(3)   not null,
    PRBEH        nvarchar(3)  not null,
    KDGFR        nvarchar(2)  not null,
    KDGF2        nvarchar(2)  not null,
    ARBER        nvarchar(8)  not null,
    EINDT        nvarchar(8)  not null,
    KONDT        nvarchar(8)  not null,
    KONSL        nvarchar(2)  not null,
    CTTYP        nvarchar(2)  not null,
    CTEDT        nvarchar(8)  not null,
    PERSG        nvarchar     not null,
    PERSK        nvarchar(2)  not null,
    WRKPL        nvarchar(40) not null,
    CTBEG        nvarchar(8)  not null,
    CTNUM        nvarchar(20) not null,
    OBJNB        nvarchar(12) not null,
    ZZ_TIPMODFOR nvarchar(2)  not null,
    constraint [PA0016~0]
        primary key (MANDT, PERNR, SUBTY, OBJPS, SPRPS, ENDDA, BEGDA, SEQNR)
)
go

create table PA0022
(
    MANDT nvarchar(3)    not null,
    PERNR nvarchar(8)    not null,
    SUBTY nvarchar(4)    not null,
    OBJPS nvarchar(2)    not null,
    SPRPS nvarchar       not null,
    ENDDA nvarchar(8)    not null,
    BEGDA nvarchar(8)    not null,
    SEQNR nvarchar(3)    not null,
    AEDTM nvarchar(8)    not null,
    UNAME nvarchar(12)   not null,
    HISTO nvarchar       not null,
    ITXEX nvarchar       not null,
    REFEX nvarchar       not null,
    ORDEX nvarchar       not null,
    ITBLD nvarchar(2)    not null,
    PREAS nvarchar(2)    not null,
    FLAG1 nvarchar       not null,
    FLAG2 nvarchar       not null,
    FLAG3 nvarchar       not null,
    FLAG4 nvarchar       not null,
    RESE1 nvarchar(2)    not null,
    RESE2 nvarchar(2)    not null,
    GRPVL nvarchar(4)    not null,
    SLART nvarchar(2)    not null,
    INSTI nvarchar(80)   not null,
    SLAND nvarchar(3)    not null,
    AUSBI nvarchar(8)    not null,
    SLABS nvarchar(2)    not null,
    ANZKL decimal(3)     not null,
    ANZEH nvarchar(3)    not null,
    SLTP1 nvarchar(5)    not null,
    SLTP2 nvarchar(5)    not null,
    JBEZ1 decimal(11, 2) not null,
    WAERS nvarchar(5)    not null,
    SLPLN nvarchar       not null,
    SLKTR nvarchar(2)    not null,
    SLRZG nvarchar       not null,
    KSBEZ nvarchar(25)   not null,
    TX122 nvarchar(40)   not null,
    SCHCD nvarchar(10)   not null,
    FACCD nvarchar(3)    not null,
    DPTMT nvarchar(40)   not null,
    EMARK nvarchar(4)    not null,
    constraint [PA0022~0]
        primary key (MANDT, PERNR, SUBTY, OBJPS, SPRPS, ENDDA, BEGDA, SEQNR)
)
go

create table PA0050
(
    MANDT nvarchar(3)   not null,
    PERNR nvarchar(8)   not null,
    SUBTY nvarchar(4)   not null,
    OBJPS nvarchar(2)   not null,
    SPRPS nvarchar      not null,
    ENDDA nvarchar(8)   not null,
    BEGDA nvarchar(8)   not null,
    SEQNR nvarchar(3)   not null,
    AEDTM nvarchar(8)   not null,
    UNAME nvarchar(12)  not null,
    HISTO nvarchar      not null,
    ITXEX nvarchar      not null,
    REFEX nvarchar      not null,
    ORDEX nvarchar      not null,
    ITBLD nvarchar(2)   not null,
    PREAS nvarchar(2)   not null,
    FLAG1 nvarchar      not null,
    FLAG2 nvarchar      not null,
    FLAG3 nvarchar      not null,
    FLAG4 nvarchar      not null,
    RESE1 nvarchar(2)   not null,
    RESE2 nvarchar(2)   not null,
    GRPVL nvarchar(4)   not null,
    ZAUSW nvarchar(8)   not null,
    ZAUVE nvarchar      not null,
    ZABAR nvarchar      not null,
    BDEGR nvarchar(3)   not null,
    ZANBE nvarchar(2)   not null,
    ZDGBE nvarchar      not null,
    ZMAIL nvarchar      not null,
    ZPINC nvarchar(4)   not null,
    GLMAX decimal(5, 2) not null,
    GLMIN decimal(5, 2) not null,
    ZTZUA decimal(5, 2) not null,
    ZMGEN nvarchar      not null,
    ZUSKZ nvarchar      not null,
    PMBDE nvarchar(2)   not null,
    GRAWG nvarchar(3)   not null,
    GRELG nvarchar(3)   not null,
    constraint [PA0050~0]
        primary key (MANDT, PERNR, SUBTY, OBJPS, SPRPS, ENDDA, BEGDA, SEQNR)
)
go

create table PA0105
(
    MANDT      nvarchar(3)   not null,
    PERNR      nvarchar(8)   not null,
    SUBTY      nvarchar(4)   not null,
    OBJPS      nvarchar(2)   not null,
    SPRPS      nvarchar      not null,
    ENDDA      nvarchar(8)   not null,
    BEGDA      nvarchar(8)   not null,
    SEQNR      nvarchar(3)   not null,
    AEDTM      nvarchar(8)   not null,
    UNAME      nvarchar(12)  not null,
    HISTO      nvarchar      not null,
    ITXEX      nvarchar      not null,
    REFEX      nvarchar      not null,
    ORDEX      nvarchar      not null,
    ITBLD      nvarchar(2)   not null,
    PREAS      nvarchar(2)   not null,
    FLAG1      nvarchar      not null,
    FLAG2      nvarchar      not null,
    FLAG3      nvarchar      not null,
    FLAG4      nvarchar      not null,
    RESE1      nvarchar(2)   not null,
    RESE2      nvarchar(2)   not null,
    GRPVL      nvarchar(4)   not null,
    USRTY      nvarchar(4)   not null,
    USRID      nvarchar(30)  not null,
    USRID_LONG nvarchar(241) not null,
    constraint [PA0105~0]
        primary key (MANDT, PERNR, SUBTY, OBJPS, SPRPS, ENDDA, BEGDA, SEQNR)
)
go

create table PA0185
(
    MANDT nvarchar(3)  not null,
    PERNR nvarchar(8)  not null,
    SUBTY nvarchar(4)  not null,
    OBJPS nvarchar(2)  not null,
    SPRPS nvarchar     not null,
    ENDDA nvarchar(8)  not null,
    BEGDA nvarchar(8)  not null,
    SEQNR nvarchar(3)  not null,
    AEDTM nvarchar(8)  not null,
    UNAME nvarchar(12) not null,
    HISTO nvarchar     not null,
    ITXEX nvarchar     not null,
    REFEX nvarchar     not null,
    ORDEX nvarchar     not null,
    ITBLD nvarchar(2)  not null,
    PREAS nvarchar(2)  not null,
    FLAG1 nvarchar     not null,
    FLAG2 nvarchar     not null,
    FLAG3 nvarchar     not null,
    FLAG4 nvarchar     not null,
    RESE1 nvarchar(2)  not null,
    RESE2 nvarchar(2)  not null,
    GRPVL nvarchar(4)  not null,
    ICTYP nvarchar(2)  not null,
    ICNUM nvarchar(30) not null,
    ICOLD nvarchar(20) not null,
    AUTH1 nvarchar(30) not null,
    DOCN1 nvarchar(20) not null,
    FPDAT nvarchar(8)  not null,
    EXPID nvarchar(8)  not null,
    ISSPL nvarchar(30) not null,
    ISCOT nvarchar(3)  not null,
    IDCOT nvarchar(3)  not null,
    OVCHK nvarchar     not null,
    ASTAT nvarchar     not null,
    AKIND nvarchar     not null,
    REJEC nvarchar(20) not null,
    USEFR nvarchar(8)  not null,
    USETO nvarchar(8)  not null,
    DATEN decimal(3)   not null,
    DATEU nvarchar(3)  not null,
    TIMES nvarchar(8)  not null,
    constraint [PA0185~0]
        primary key (MANDT, PERNR, SUBTY, OBJPS, SPRPS, ENDDA, BEGDA, SEQNR)
)
go

create table T001P
(
    MANDT nvarchar(3)  not null,
    WERKS nvarchar(4)  not null,
    BTRTL nvarchar(4)  not null,
    BTEXT nvarchar(15) not null,
    MOLGA nvarchar(2)  not null,
    MOURA nvarchar(2)  not null,
    TRFGB nvarchar(2)  not null,
    TRFAR nvarchar(2)  not null,
    MOABW nvarchar(2)  not null,
    MOABT nvarchar(2)  not null,
    MOTAT nvarchar(2)  not null,
    MOVER nvarchar(2)  not null,
    URLKL nvarchar(2)  not null,
    JUPER nvarchar(4)  not null,
    MOBDE nvarchar(2)  not null,
    MOZKO nvarchar(2)  not null,
    MOPTB nvarchar(2)  not null,
    WKTYP nvarchar     not null,
    MOSTA nvarchar(2)  not null,
    MOBUR nvarchar(2)  not null,
    MOFID nvarchar(2)  not null,
    MOSID nvarchar(2)  not null,
    MODSZ nvarchar(2)  not null,
    constraint [T001P~0]
        primary key (MANDT, WERKS, BTRTL)
)
go

create table T005T
(
    MANDT      nvarchar(3)  not null,
    SPRAS      nvarchar     not null,
    LAND1      nvarchar(3)  not null,
    LANDX      nvarchar(15) not null,
    NATIO      nvarchar(15) not null,
    LANDX50    nvarchar(50) not null,
    NATIO50    nvarchar(50) not null,
    PRQ_SPREGT nvarchar(30) not null,
    constraint [T005T~0]
        primary key (MANDT, SPRAS, LAND1)
)
go

create table T500P
(
    MANDT nvarchar(3)  not null,
    PERSA nvarchar(4)  not null,
    MOLGA nvarchar(2)  not null,
    BUKRS nvarchar(4)  not null,
    NAME1 nvarchar(30) not null,
    NAME2 nvarchar(30) not null,
    STRAS nvarchar(30) not null,
    PFACH nvarchar(10) not null,
    PSTLZ nvarchar(10) not null,
    ORT01 nvarchar(25) not null,
    LAND1 nvarchar(3)  not null,
    REGIO nvarchar(3)  not null,
    COUNC nvarchar(3)  not null,
    CITYC nvarchar(4)  not null,
    ADRNR nvarchar(10) not null,
    constraint [T500P~0]
        primary key (MANDT, PERSA)
)
go

create table T501T
(
    MANDT nvarchar(3)  not null,
    SPRSL nvarchar     not null,
    PERSG nvarchar     not null,
    PTEXT nvarchar(20) not null,
    constraint [T501T~0]
        primary key (MANDT, SPRSL, PERSG)
)
go

create table T502T
(
    MANDT nvarchar(3) not null,
    SPRSL nvarchar    not null,
    FAMST nvarchar    not null,
    FTEXT nvarchar(6) not null,
    constraint [T502T~0]
        primary key (MANDT, SPRSL, FAMST)
)
go

create table T503T
(
    MANDT nvarchar(3)  not null,
    SPRSL nvarchar     not null,
    PERSK nvarchar(2)  not null,
    PTEXT nvarchar(20) not null,
    constraint [T503T~0]
        primary key (MANDT, SPRSL, PERSK)
)
go

create table T527X
(
    MANDT nvarchar(3)  not null,
    SPRSL nvarchar     not null,
    ORGEH nvarchar(8)  not null,
    ENDDA nvarchar(8)  not null,
    BEGDA nvarchar(8)  not null,
    ORGTX nvarchar(25) not null,
    MAINT nvarchar     not null,
    constraint [T527X~0]
        primary key (MANDT, SPRSL, ORGEH, ENDDA)
)
go
